### ISSUE TITLE
Provide a way to cleanup after aborted requests

### ISSUE THREAD

**Issue by kch** [zombocom/rack-timeout#49]
Especially, aborting mid sql operation can hose sql connections that need to be reset. We'll only provide the means to perform cleanup actions, but no specific cleanup code.

That said, because the SQL case is so common, documentation should provide an example for Rails/ActiveRecord. Such sample code is welcome in the comments.

Something around observers is probably the best option here. See #40 for discussion.

**Comment by collimarco** [comment]
What do you use to terminate the current query / clear connection?

I see this:
```
ActiveRecord::Base.connection.reset!
```

However on PG 11 this query reveals that the query (e.g. sleep) is not terminated:

```
SELECT * FROM pg_stat_activity WHERE pg_stat_activity.usename='your user';
```

**Comment by wuputah** [comment]
I continue to think `statement_timeout` is overall the best bet as mentioned in #151. The `connection.reset!` option may free up the connection in the pool, but yes, it won't kill the query. You can then `select pg_cancel_backend(pid)` or `select pg_terminate_backend(pid)` (Postgres only) with a new connection, but knowing what pid to kill is a problem, and it's also not DB agnostic.

**Comment by schneems** [comment]
> Especially, aborting mid sql operation can hose sql connections that need to be reset.

I don't think that Rack::Timeout can actually interrupt the request midquery. Thread.raise only executes when the code returns from the native extension back to Ruby land.

I think this is related though: https://www.schneems.com/2017/02/21/the-oldest-bug-in-ruby-why-racktimeout-might-hose-your-server/

I don't think this is an issue that rack-timeout can solve. I believe that changes need to be made in Ruby, possibly introducing a new API to "safely" raise on another thread, basically don't raise an exception while currently inside of an ensure block. I brought this up to Matz, he said that there's a halting problem that there's no guarantee that the code will ever exit the ensure block, so we would also have to have a timeout on this "safe" timeout, but it would still be better than what we've currently got. He told me to bring it up to Koichi, but Koichi had a kid and then Covid happened and i've not seen him since. I could try to move to async communication.

I'm open to other alternative suggestions for fixes here. The only "safe" way to kill a thread is to abort the entire process. We could perhaps introduce experimental config to enable that behavior instead of raising on the thread. I've experimented with Puma before and I think the behavior of TERM-ing a puma process does what you want out of the box. You would need to kill the thread, then shut down the process and puma will re-boot another process for you.

The only downside with this approach is if rack-timeout is firing so often that it's constantly re-booting processes. I'm not totally sure if that's a valid use case for rack-timeout because in that case they're hitting this race condition anyway.

**Comment by schneems** [comment]
I literally forgot I added this https://github.com/sharpstone/rack-timeout/pull/157

I've not had any customers with this persistent H12 problem since I added that so I don't have much feedback. I did add it to our docs here https://devcenter.heroku.com/articles/h12-request-timeout-in-ruby-mri#rack-timeout-limitations so there might be some correlation with the reduction in H12 related tickets, but I don't know.

**Comment by mtsmfm** [comment]
@schneems Awesome improvement!
I've found not only connection but also so many codes can be broken.
For example, a scope which applied in timed out request may apply to next request.
What do you think about making `term_on_timeout: true` by default?

https://github.com/sharpstone/rack-timeout/issues/169

**Comment by schneems** [comment]
>  What do you think about making term_on_timeout: true by default?

I think it's risky unless we can detect you're in a forked environment. We would need some sort of integration or detection. Also the main architect of rack-timeout is @wuputah so I would want his thoughts as well.

**Comment by schneems** [comment]
> Also the main architect of rack-timeout is @wuputah so I would want his thoughts as well.

It's been about a year and a half. I think I could move forward with making it the default. However I would still like a good way to detect if you're in a fork or not.

**Comment by wuputah** [comment]
Personally, I would not make `term_on_timeout` the default. That could bring down someone's app if it's not forked or shutdown their web server locally. It should be opt-in behavior.

**Comment by fxn** [comment]
On the topic of interrupting queries in the server, if that is what you want, in Postgres something that I've tested cancels even `pg_sleep()` is to use its SQL API from a different connection (assuming you are able to checkout one):

```ruby
pid = ActiveRecord::Base.connection.raw_connection.backend_pid
Thread.new do
  ActiveRecord::Base.connection_pool.with_connection do |conn|
    conn.execute("SELECT pg_cancel_backend(#{pid})")
  end
  puts "cancelled"
end.join
```

**Comment by schneems** [comment]
@fxn neat! Do you know if that plays well with connection poolers like pgbouncer? I.e. would it kill the PG connection which might be hosting multiple in-flight rails requests, or would it terminate the connection to pgbouncer? My guess would be the first one.

> Personally, I would not make term_on_timeout the default. That could bring down someone's app if it's not forked or shutdown their web server locally. It should be opt-in behavior.

We could propose an an API that lets webservers indicate requests are running in a SIGTERM-able environment.

One option could be rack. Possibly an optional extension to Rack that allows web servers to specify that requests are being processed in a fork. Maybe something like “app.can_term?”

I’m unsure on implementation details though.

**Comment by fxn** [comment]
@schneems I don't know. `pg_cancel_backend()` is documented to cancel the current query without killing the connection. I have to say I have done only synthetic tests about this, don't have it yet in production. But the project I am exploring this for does not use PgBouncer.

**Comment by fxn** [comment]
I have seen that `pg` has API to cancel asynchronously ([source code](https://github.com/ged/ruby-pg/blob/6629dec6656f7ca27619e4675b45225d9e422112/lib/pg/connection.rb#L582)). The snippet above can be replaced with this one-liner:

```ruby
ActiveRecord::Base.connection.raw_connection.cancel
```

according to my still synthetic tests.
